"""Change tables

Revision ID: 4e51ab2595b3
Revises: 
Create Date: 2024-11-28 10:44:18.179833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e51ab2595b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises_data',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('exercise_met', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('foods',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('food_calories_100gr', sa.Integer(), nullable=False),
    sa.Column('food_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('food_id'),
    sa.UniqueConstraint('food_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('user_birthday', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('user_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('burned_calories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_time', sa.Float(), nullable=False),
    sa.Column('burned_calories_number', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises_data.exercise_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'created_at')
    )
    op.create_table('calories_consumptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eaten_food_id', sa.Integer(), nullable=False),
    sa.Column('eaten_food_mass', sa.Integer(), nullable=False),
    sa.Column('eaten_calories_number', sa.Integer(), nullable=False),
    sa.Column('eaten_calories_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['eaten_food_id'], ['foods.food_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'eaten_calories_created_at')
    )
    op.create_table('users_data',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_height', sa.Integer(), nullable=False),
    sa.Column('user_weight', sa.Float(), nullable=False),
    sa.Column('user_activity_level', sa.Integer(), nullable=False),
    sa.Column('user_tdee_number', sa.Integer(), nullable=False),
    sa.Column('user_bmi_number', sa.Integer(), nullable=False),
    sa.Column('data_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'data_created_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_data')
    op.drop_table('calories_consumptions')
    op.drop_table('burned_calories')
    op.drop_table('users')
    op.drop_table('foods')
    op.drop_table('exercises_data')
    # ### end Alembic commands ###
