"""New total table

Revision ID: 683d5524bda3
Revises: 79b5a2054cfd
Create Date: 2024-11-26 10:58:35.106746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '683d5524bda3'
down_revision: Union[str, None] = '79b5a2054cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('total calories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_calories_eaten', sa.String(), nullable=False),
    sa.Column('total_calories_burned', sa.Float(), nullable=False),
    sa.Column('daily_tdee', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'created_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('total calories')
    # ### end Alembic commands ###
