"""New version of tables

Revision ID: 79b5a2054cfd
Revises: 
Create Date: 2024-11-25 18:21:16.407488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b5a2054cfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises_met',
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('exercise_met', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('exercise_name')
    )
    op.create_table('foods',
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('food_calories', sa.Integer(), nullable=False),
    sa.Column('food_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('food_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('activity_level', sa.Integer(), nullable=False),
    sa.Column('user_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bmis',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bmi_number', sa.Integer(), nullable=False),
    sa.Column('bmi_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'bmi_created_at')
    )
    op.create_table('burned calories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('exercise_met', sa.Float(), nullable=False),
    sa.Column('exercise_time', sa.Float(), nullable=False),
    sa.Column('burned_calories_number', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'created_at')
    )
    op.create_table('calories_consumptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eaten_food_name', sa.String(), nullable=False),
    sa.Column('eaten_food_mass', sa.Integer(), nullable=False),
    sa.Column('eaten_calories_number', sa.Integer(), nullable=False),
    sa.Column('eaten_calories_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'eaten_calories_created_at')
    )
    op.create_table('tdees',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tdee_number', sa.Integer(), nullable=False),
    sa.Column('tdee_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tdee_created_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tdees')
    op.drop_table('calories_consumptions')
    op.drop_table('burned calories')
    op.drop_table('bmis')
    op.drop_table('users')
    op.drop_table('foods')
    op.drop_table('exercises_met')
    # ### end Alembic commands ###
