"""New table totals

Revision ID: abd0d08e32cf
Revises: 4e51ab2595b3
Create Date: 2024-12-03 14:22:58.310915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd0d08e32cf'
down_revision: Union[str, None] = '4e51ab2595b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_burned_calories_number', sa.Float(), nullable=False),
    sa.Column('total_eaten_calories_number', sa.Integer(), nullable=False),
    sa.Column('result_tdee', sa.Float(), nullable=False),
    sa.Column('eaten_calories_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'eaten_calories_created_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('totals')
    # ### end Alembic commands ###
